In [1]:
import malariagen_data

In [2]:
ag3 = malariagen_data.Ag3(
    "simplecache::gs://vo_agam_release",
    simplecache=dict(cache_storage="../gcs_cache"),
    results_cache="results_cache",
)
ag3

<MalariaGEN Ag3 API client>
Storage URL             : simplecache::gs://vo_agam_release
Data releases available : 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8
Results cache           : /home/aliman/github/alimanfoo/malariagen-data-python/notebooks/results_cache
Cohorts analysis        : 20231019
AIM analysis            : 20220528
Site filters analysis   : dt_20200416
Software version        : malariagen_data 0.0.0
Client location         : unknown
---
Please note that data are subject to terms of use,
for more information see https://www.malariagen.net/data
or contact data@malariagen.net. For API documentation see 
https://malariagen.github.io/malariagen-data-python/v0.0.0/Ag3.html

In [3]:
af1 = malariagen_data.Af1(
    "simplecache::gs://vo_afun_release",
    simplecache=dict(cache_storage="../gcs_cache"),
    results_cache="results_cache",
)
af1

<MalariaGEN Af1 API client>
Storage URL             : simplecache::gs://vo_afun_release
Data releases available : 1.0
Results cache           : /home/aliman/github/alimanfoo/malariagen-data-python/notebooks/results_cache
Cohorts analysis        : 20231122
Site filters analysis   : dt_20200416
Software version        : malariagen_data 0.0.0
Client location         : unknown
---
Please note that data are subject to terms of use,
for more information see https://www.malariagen.net/data
or contact data@malariagen.net. For API documentation see 
https://malariagen.github.io/malariagen-data-python/v0.0.0/Af1.html

In [4]:
!rm -rf results_cache

In [5]:
%%time
dist, samples, n_snps = ag3.biallelic_diplotype_pairwise_distances(
    region="3L:15,000,000-16,000,000",
    sample_sets="AG1000G-FR",
    n_snps=10_000,
)

Compute SNP allele counts:   0%|          | 0/8 [00:00<?, ?it/s]

Compute biallelic diplotypes:   0%|          | 0/20 [00:00<?, ?it/s]

CPU times: user 2.9 s, sys: 242 ms, total: 3.14 s
Wall time: 7.6 s


In [6]:
%%time
dist, samples, n_snps = ag3.biallelic_diplotype_pairwise_distances(
    region="3L:15,000,000-16,000,000",
    sample_sets="AG1000G-FR",
    n_snps=10_000,
)

CPU times: user 44.6 ms, sys: 6.12 ms, total: 50.7 ms
Wall time: 6.63 ms


In [7]:
dist

array([5192., 3345., 4076., 5103., 5006., 1776., 4370., 4906., 4242.,
       4283., 4933., 4509., 5054., 3861., 4606., 4273., 4464., 4688.,
       4178., 3895., 3848., 5435., 5209., 6060., 2029., 2440., 4984.,
       2920., 3458., 4304., 3299., 4043., 4203., 2088., 3425., 5910.,
       4199., 3856., 4132., 4890., 5501., 5266., 2755., 4801., 4542.,
       4697., 2855., 4065., 4749., 4857., 5104., 4956., 4152., 5047.,
       3200., 5441., 4152., 4507., 3545., 4101., 3044., 4189., 5804.,
       5903., 5938., 4216., 5748., 5504., 4734., 5491., 5241., 6541.,
       5542., 5487., 2434., 5029., 4002., 5616., 4966., 5353., 5426.,
       6381., 2509., 4869., 2687., 2263., 4045., 3296., 3428., 3768.,
       1567., 2456., 5675., 3066., 3535., 2943., 3609., 4604., 5483.,
       4172., 4714., 3494., 2200., 3600., 4677., 3399., 3715., 3246.,
       2415., 5598., 3339., 5034., 2756., 3638., 4443., 5508., 2205.,
       4092., 4586., 4100., 4239., 4611., 4221., 4754., 3545., 4742.,
       3931., 4048.,

In [8]:
samples

array(['AP0007-C', 'AP0021-C', 'AP0019-C', 'AP0020-C', 'AP0009-C',
       'AP0002-C', 'AP0034-C', 'AP0035-C', 'AP0031-C', 'AP0008-C',
       'AP0011-C', 'AP0032-C', 'AP0010-C', 'AP0025-C', 'AP0022-C',
       'AP0006-C', 'AP0030-C', 'AP0023-C', 'AP0033-C', 'AP0005-C',
       'AP0014-Cx', 'AP0013-Cx', 'AP0017-Cx'], dtype='<U24')

In [9]:
n_snps

10429

In [10]:
%%time
dist, samples, n_snps = ag3.biallelic_diplotype_pairwise_distances(
    region="3L:15,000,000-16,000,000",
    sample_sets="AG1000G-BF-A",
    n_snps=10_000,
)

Compute SNP allele counts:   0%|          | 0/36 [00:00<?, ?it/s]

Compute biallelic diplotypes:   0%|          | 0/68 [00:00<?, ?it/s]

CPU times: user 3.62 s, sys: 359 ms, total: 3.98 s
Wall time: 6.87 s


In [11]:
dist

array([ 971., 1074., 1016., ..., 1063., 1037.,  952.], dtype=float32)

In [12]:
dist[:100]

array([ 971., 1074., 1016., 1090., 1050., 1067., 1041., 1055., 1090.,
        935., 1017., 1060., 1104., 1043., 1098.,  904.,  857., 1034.,
       1071., 1055., 1058., 1026., 1060., 1062.,  917.,  925.,  944.,
        957., 1060., 1093., 1085., 1068.,  970.,  929.,  963.,  965.,
        955.,  942., 1064.,  960.,  935.,  936.,  926., 1059., 1078.,
       1094., 1044., 1024.,  880.,  924.,  914.,  953.,  922.,  930.,
        983., 1017.,  929.,  964.,  973.,  944.,  968.,  928.,  962.,
        926.,  936.,  972.,  957., 1001.,  935.,  934.,  959.,  960.,
        971.,  975.,  998.,  946.,  919.,  909.,  924.,  977., 1015.,
       1060., 1108., 1096., 1037., 1063., 1061., 1060., 1085., 1093.,
       1029., 1044., 1061., 1058., 1070.,  940.,  958.,  965.,  952.,
        944.], dtype=float32)

In [13]:
samples

array(['AB0085-Cx', 'AB0086-Cx', 'AB0087-C', 'AB0088-C', 'AB0089-Cx',
       'AB0090-C', 'AB0091-C', 'AB0092-C', 'AB0094-Cx', 'AB0095-Cx',
       'AB0096-C', 'AB0097-Cx', 'AB0098-Cx', 'AB0099-Cx', 'AB0100-C',
       'AB0101-C', 'AB0103-C', 'AB0104-Cx', 'AB0109-C', 'AB0110-C',
       'AB0111-C', 'AB0112-C', 'AB0113-C', 'AB0114-C', 'AB0115-C',
       'AB0116-C', 'AB0117-C', 'AB0118-C', 'AB0119-C', 'AB0121-C',
       'AB0122-C', 'AB0123-C', 'AB0124-C', 'AB0126-Cx', 'AB0127-C',
       'AB0128-C', 'AB0129-C', 'AB0130-Cx', 'AB0131-Cx', 'AB0132-C',
       'AB0133-C', 'AB0134-C', 'AB0135-C', 'AB0136-Cx', 'AB0137-Cx',
       'AB0138-Cx', 'AB0139-C', 'AB0140-C', 'AB0142-C', 'AB0143-Cx',
       'AB0144-C', 'AB0145-C', 'AB0146-Cx', 'AB0147-C', 'AB0148-Cx',
       'AB0150-Cx', 'AB0151-Cx', 'AB0153-C', 'AB0155-Cx', 'AB0157-Cx',
       'AB0158-Cx', 'AB0159-C', 'AB0160-Cx', 'AB0161-C', 'AB0162-C',
       'AB0164-C', 'AB0165-C', 'AB0166-C', 'AB0167-C', 'AB0169-C',
       'AB0170-C', 'AB0171-Cx', 'AB017

In [14]:
n_snps

10258

In [15]:
%%time
dist, samples, n_snps = ag3.biallelic_diplotype_pairwise_distances(
    region="3L:15,000,000-16,000,000",
    sample_sets=["3.0"],
    n_snps=10_000,
)

Compute SNP allele counts:   0%|          | 0/696 [00:00<?, ?it/s]

Compute biallelic diplotypes:   0%|          | 0/1188 [00:00<?, ?it/s]

CPU times: user 1min 50s, sys: 910 ms, total: 1min 51s
Wall time: 35.3 s


In [16]:
%%time
dist, samples, n_snps = ag3.biallelic_diplotype_pairwise_distances(
    region="3L:15,000,000-16,000,000",
    sample_sets=["3.0"],
    n_snps=10_000,
)

CPU times: user 33.9 ms, sys: 38 µs, total: 33.9 ms
Wall time: 31.7 ms


In [17]:
gn, samples = ag3.biallelic_diplotypes(
    region="3L:15,000,000-16,000,000",
    sample_sets=["3.0"],
    n_snps=10_000,
)

In [18]:
import numpy as np

In [19]:
X = np.ascontiguousarray(gn.T)

In [20]:
import scipy.spatial.distance as ssd

In [21]:
%%time 
dist2 = ssd.pdist(X, metric="cityblock")

CPU times: user 36.4 s, sys: 40.8 ms, total: 36.5 s
Wall time: 36.5 s


In [22]:
import malariagen_data.util as mu

In [24]:
%%time
dist3 = mu.biallelic_diplotype_pdist(X, distfun=mu.biallelic_diplotype_cityblock)

CPU times: user 1min 9s, sys: 11.7 ms, total: 1min 9s
Wall time: 8.81 s
