In [2]:
import malariagen_data
import allel
import pandas as pd
import numpy as np


In [3]:
ag3 = malariagen_data.Ag3(
    "simplecache::gs://vo_agam_release",
    simplecache=dict(cache_storage="../gcs_cache"),
)
ag3


<MalariaGEN Ag3 API client>
Storage URL             : simplecache::gs://vo_agam_release
Data releases available : 3.0
Results cache           : None
Cohorts analysis        : 20230223
AIM analysis            : 20220528
Site filters analysis   : dt_20200416
Software version        : malariagen_data 0.0.0
Client location         : unknown
---
Please note that data are subject to terms of use,
for more information see https://www.malariagen.net/data
or contact data@malariagen.net. For API documentation see 
https://malariagen.github.io/vector-data/ag3/api.html

In [4]:
ds = ag3.snp_calls(region="3L", sample_sets="AG1000G-BF-A")
ds


<xarray.Dataset>
Dimensions:                             (variants: 40758473, alleles: 4,
                                         samples: 181, ploidy: 2)
Coordinates:
    variant_position                    (variants) int32 dask.array<chunksize=(524288,), meta=np.ndarray>
    variant_contig                      (variants) uint8 dask.array<chunksize=(524288,), meta=np.ndarray>
    sample_id                           (samples) <U24 dask.array<chunksize=(181,), meta=np.ndarray>
Dimensions without coordinates: variants, alleles, samples, ploidy
Data variables:
    variant_allele                      (variants, alleles) |S1 dask.array<chunksize=(524288, 1), meta=np.ndarray>
    variant_filter_pass_gamb_colu_arab  (variants) bool dask.array<chunksize=(300000,), meta=np.ndarray>
    variant_filter_pass_gamb_colu       (variants) bool dask.array<chunksize=(300000,), meta=np.ndarray>
    variant_filter_pass_arab            (variants) bool dask.array<chunksize=(300000,), meta=np.ndarray>
    call_genotype                       (variants, samples, ploidy) int8 dask.array<chunksize=(300000, 50, 2), meta=np.ndarray>
    call_GQ                             (variants, samples) int16 dask.array<chunksize=(300000, 50), meta=np.ndarray>
    call_MQ                             (variants, samples) int16 dask.array<chunksize=(300000, 50), meta=np.ndarray>
    call_AD                             (variants, samples, alleles) int16 dask.array<chunksize=(300000, 50, 4), meta=np.ndarray>
    call_genotype_mask                  (variants, samples, ploidy) bool dask.array<chunksize=(300000, 50, 2), meta=np.ndarray>
Attributes:
    contigs:  ('2R', '2L', '3R', '3L', 'X')

In [5]:
ds2 = ds.isel(variants=slice(10_000_000, 11_000_000))
ds2


<xarray.Dataset>
Dimensions:                             (variants: 1000000, alleles: 4,
                                         samples: 181, ploidy: 2)
Coordinates:
    variant_position                    (variants) int32 dask.array<chunksize=(485760,), meta=np.ndarray>
    variant_contig                      (variants) uint8 dask.array<chunksize=(485760,), meta=np.ndarray>
    sample_id                           (samples) <U24 dask.array<chunksize=(181,), meta=np.ndarray>
Dimensions without coordinates: variants, alleles, samples, ploidy
Data variables:
    variant_allele                      (variants, alleles) |S1 dask.array<chunksize=(485760, 1), meta=np.ndarray>
    variant_filter_pass_gamb_colu_arab  (variants) bool dask.array<chunksize=(200000,), meta=np.ndarray>
    variant_filter_pass_gamb_colu       (variants) bool dask.array<chunksize=(200000,), meta=np.ndarray>
    variant_filter_pass_arab            (variants) bool dask.array<chunksize=(200000,), meta=np.ndarray>
    call_genotype                       (variants, samples, ploidy) int8 dask.array<chunksize=(200000, 50, 2), meta=np.ndarray>
    call_GQ                             (variants, samples) int16 dask.array<chunksize=(200000, 50), meta=np.ndarray>
    call_MQ                             (variants, samples) int16 dask.array<chunksize=(200000, 50), meta=np.ndarray>
    call_AD                             (variants, samples, alleles) int16 dask.array<chunksize=(200000, 50, 4), meta=np.ndarray>
    call_genotype_mask                  (variants, samples, ploidy) bool dask.array<chunksize=(200000, 50, 2), meta=np.ndarray>
Attributes:
    contigs:  ('2R', '2L', '3R', '3L', 'X')

In [6]:
gt = ds2["call_genotype"].values
gt


array([[[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       ...,

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]]], dtype=int8)

In [7]:
gt2 = allel.GenotypeArray(gt)
gt2


<GenotypeArray shape=(1000000, 181, 2) dtype=int8>
0/0 0/0 0/0 0/0 0/0 ... 0/0 0/0 0/0 0/0 0/0
0/0 0/0 0/0 0/0 0/0 ... 0/0 0/0 0/0 0/0 0/0
0/0 0/0 0/0 0/0 0/0 ... 0/0 0/0 0/0 0/0 0/0
...
0/0 0/0 0/0 0/0 0/0 ... 0/0 0/0 0/0 0/0 0/0
0/0 0/0 0/0 0/0 0/0 ... 0/0 0/0 0/0 0/0 0/0
0/0 0/0 0/0 0/0 0/0 ... 0/0 0/0 0/0 0/0 0/0

In [11]:
np.bincount(gt.flatten() + 1) / gt.size


array([0.09992149, 0.88301928, 0.00563986, 0.00664629, 0.00477307])

In [19]:
missing_fraction = gt2.count_missing() / (gt2.n_variants * gt2.n_samples)
missing_fraction


0.09992149171270719

In [17]:
allele_counts = np.bincount(gt.flatten() + 1)[1:]
allele_counts


array([319652981,   2041631,   2405958,   1727850])

In [18]:
allele_fractions = allele_counts / np.sum(allele_counts)
allele_fractions


array([0.98104696, 0.00626597, 0.00738413, 0.00530294])

In [21]:
gt_sim = np.random.choice(4, size=gt.shape, replace=True, p=allele_fractions)
gt_sim


array([[[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       ...,

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]]])

In [22]:
n_calls = gt_sim.shape[0] * gt_sim.shape[1]
n_calls


181000000

In [23]:
gt_sim_flat = gt_sim.reshape(-1, 2)
gt_sim_flat


array([[0, 0],
       [0, 0],
       [0, 0],
       ...,
       [0, 0],
       [0, 0],
       [0, 0]])

In [24]:
loc_missing = np.random.choice(
    n_calls,
    size=int(missing_fraction * n_calls),
    replace=False,
)
loc_missing


array([152798522,  44788626, 155118648, ...,  19173207, 150473262,
        55107223])

In [26]:
gt_sim_flat[loc_missing] = -1


In [27]:
gt_sim


array([[[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        ...,
        [ 0,  0],
        [ 0,  0],
        [ 0,  0]],

       [[ 0,  0],
        [ 0,  1],
        [ 0,  0],
        ...,
        [ 0,  0],
        [ 0,  0],
        [ 0,  0]],

       [[-1, -1],
        [ 0,  0],
        [ 0,  0],
        ...,
        [ 0,  0],
        [ 0,  0],
        [ 0,  0]],

       ...,

       [[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        ...,
        [ 0,  0],
        [-1, -1],
        [ 0,  0]],

       [[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        ...,
        [-1, -1],
        [ 0,  0],
        [ 0,  0]],

       [[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        ...,
        [ 0,  0],
        [ 0,  0],
        [ 0,  0]]])

In [29]:
np.bincount(gt_sim.flatten() + 1) / gt_sim.size


array([0.09992149, 0.88301611, 0.00563512, 0.00665073, 0.00477654])

In [30]:
np.bincount(gt.flatten() + 1) / gt.size


array([0.09992149, 0.88301928, 0.00563986, 0.00664629, 0.00477307])

In [31]:
allel.GenotypeArray(gt).count_missing()


18085790

In [32]:
allel.GenotypeArray(gt_sim).count_missing()


18085790

In [33]:
allel.GenotypeArray(gt).count_hom_ref()


158583522

In [34]:
allel.GenotypeArray(gt_sim).count_hom_ref()


156796197

In [35]:
allel.GenotypeArray(gt).count_hom_alt()


1818838

In [36]:
allel.GenotypeArray(gt_sim).count_hom_alt()


19820

In [37]:
gq = ds2["call_GQ"].values


In [39]:
import plotly.express as px


In [40]:
px.histogram(gq.flatten()[:10_000])


In [42]:
p_gq = np.bincount(gq[gq >= 0].flatten()) / gq.size
p_gq


array([4.53535912e-05, 1.05143646e-04, 1.03099448e-04, 1.81086851e-02,
       1.06790055e-04, 1.05165746e-04, 1.24331657e-02, 1.04751381e-04,
       1.08519337e-04, 1.04769171e-02, 1.05823204e-04, 1.13193370e-04,
       9.51060773e-03, 1.08933702e-04, 1.21458564e-04, 9.03166851e-03,
       1.11707182e-04, 1.34138122e-04, 8.95126519e-03, 1.11397790e-04,
       1.43160221e-04, 8.96703315e-03, 1.11839779e-04, 1.42889503e-04,
       9.25255801e-03, 1.14475138e-04, 1.44060773e-04, 9.66389503e-03,
       1.21469613e-04, 1.28944751e-04, 1.02797459e-02, 1.27911602e-04,
       1.36270718e-04, 1.09753536e-02, 1.28348066e-04, 1.32558011e-04,
       1.17159448e-02, 1.30883978e-04, 1.34325967e-04, 1.25336298e-02,
       1.42867403e-04, 1.48513812e-04, 1.33958508e-02, 1.53215470e-04,
       1.59939227e-04, 1.42095470e-02, 1.63762431e-04, 1.71933702e-04,
       1.49593536e-02, 1.71541436e-04, 1.82110497e-04, 1.57312099e-02,
       1.80690608e-04, 1.94712707e-04, 1.65045912e-02, 1.79414365e-04,
      

In [44]:
px.line(p_gq)
