In [1]:
import malariagen_data
ag3 = malariagen_data.Ag3("gs://vo_agam_release/")
ag3

In [2]:
root = ag3.open_site_annotations()
root

<zarr.hierarchy.Group '/'>

In [3]:
print(root.tree())

/
 ├── codon_degeneracy
 │   ├── 2L (49364325,) int8
 │   ├── 2R (61545105,) int8
 │   ├── 3L (41963435,) int8
 │   ├── 3R (53200684,) int8
 │   ├── Mt (15363,) int8
 │   ├── UNKN (42389979,) int8
 │   ├── X (24393108,) int8
 │   └── Y_unplaced (237045,) int8
 ├── codon_nonsyn
 │   ├── 2L (49364325,) uint8
 │   ├── 2R (61545105,) uint8
 │   ├── 3L (41963435,) uint8
 │   ├── 3R (53200684,) uint8
 │   ├── Mt (15363,) uint8
 │   ├── UNKN (42389979,) uint8
 │   ├── X (24393108,) uint8
 │   └── Y_unplaced (237045,) uint8
 ├── codon_position
 │   ├── 2L (49364325,) int8
 │   ├── 2R (61545105,) int8
 │   ├── 3L (41963435,) int8
 │   ├── 3R (53200684,) int8
 │   ├── Mt (15363,) int8
 │   ├── UNKN (42389979,) int8
 │   ├── X (24393108,) int8
 │   └── Y_unplaced (237045,) int8
 ├── seq_cls
 │   ├── 2L (49364325,) uint8
 │   ├── 2R (61545105,) uint8
 │   ├── 3L (41963435,) uint8
 │   ├── 3R (53200684,) uint8
 │   ├── Mt (15363,) uint8
 │   ├── UNKN (42389979,) uint8
 │   ├── X (24393108,) uint8
 

In [4]:
df_geneset = ag3.geneset()
df_geneset

seqid      source             type   start       end  score  \
0               2L  VectorBase       chromosome       1  49364325    NaN   
1               2L  VectorBase             gene  157348    186936    NaN   
2               2L  VectorBase             mRNA  157348    181305    NaN   
3               2L  VectorBase  three_prime_UTR  157348    157495    NaN   
4               2L  VectorBase             exon  157348    157623    NaN   
...            ...         ...              ...     ...       ...    ...   
196140  Y_unplaced  VectorBase   five_prime_UTR   47932     48111    NaN   
196141  Y_unplaced  VectorBase             exon   47932     48138    NaN   
196142  Y_unplaced  VectorBase              CDS   48112     48138    NaN   
196143  Y_unplaced  VectorBase             exon   48301     48385    NaN   
196144  Y_unplaced  VectorBase              CDS   48301     48385    NaN   

       strand  phase             ID         Parent              Name  
0         NaN    NaN             2L            NaN               NaN  
1           -    NaN     AGAP004677            NaN               NaN  
2           -    NaN  AGAP004677-RA     AGAP004677               NaN  
3           -    NaN            NaN  AGAP004677-RA               NaN  
4           -    NaN            NaN  AGAP004677-RA  AGAP004677-RB-E4  
...       ...    ...            ...            ...               ...  
196140      +    NaN            NaN  AGAP029375-RA               NaN  
196141      +    NaN            NaN  AGAP029375-RA  AGAP029375-RA-E2  
196142      +    0.0  AGAP029375-PA  AGAP029375-RA               NaN  
196143      +    NaN            NaN  AGAP029375-RA  AGAP029375-RA-E3  
196144      +    0.0  AGAP029375-PA  AGAP029375-RA               NaN  

[196145 rows x 11 columns]

In [5]:
df_geneset.query("ID == 'AGAP004707'")

seqid      source  type    start      end  score strand  phase  \
716    2L  VectorBase  gene  2358158  2431617    NaN      +    NaN   

             ID Parent  Name  
716  AGAP004707    NaN  para

In [6]:
root["codon_position/2L"][2358157:2358166]

array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int8)

In [7]:
root["codon_degeneracy/2L"][2358150:2358166]

array([-1, -1, -1, -1, -1, -1, -1,  3,  1,  3,  1,  1,  4,  1,  1,  2],
      dtype=int8)

In [8]:
root["codon_nonsyn/2L"][2358150:2358166]

array([0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 0, 3, 3, 2], dtype=uint8)

In [9]:
root["seq_cls/2L"][2358150:2358166]

array([1, 1, 1, 1, 1, 1, 1, 5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=uint8)

In [10]:
root["seq_flen/2L"][2358150:2358166]

array([26020, 26020, 26020, 26020, 26020, 26020, 26020,   147,   147,
         147,   147,   147,   147,   147,   147,   147], dtype=uint32)

In [11]:
root["seq_relpos_start/2L"][2358150:2358166]

array([26013, 26014, 26015, 26016, 26017, 26018, 26019,     0,     1,
           2,     3,     4,     5,     6,     7,     8], dtype=uint32)

In [12]:
root["seq_relpos_stop/2L"][2358150:2358166]

array([  6,   5,   4,   3,   2,   1,   0, 146, 145, 144, 143, 142, 141,
       140, 139, 138], dtype=uint32)

In [13]:
d = ag3.site_annotations(contig="2L", field="seq_cls")
d

dask.array<getitem, shape=(48525747,), dtype=uint8, chunksize=(771170,), chunktype=numpy.ndarray>

In [15]:
from malariagen_data import SiteClass

In [16]:
import numpy as np

In [17]:
s = np.bincount(d).compute()

In [18]:
s

array([  892457, 12558080, 10410051,   750923,  1561113,   697336,
        2395901,  1176587,  5153084, 11478176,  1452039])

In [19]:
list(SiteClass)

[<SiteClass.UPSTREAM: 1>,
 <SiteClass.DOWNSTREAM: 2>,
 <SiteClass.UTR5: 3>,
 <SiteClass.UTR3: 4>,
 <SiteClass.CDS_FIRST: 5>,
 <SiteClass.CDS_MID: 6>,
 <SiteClass.CDS_LAST: 7>,
 <SiteClass.INTRON_FIRST: 8>,
 <SiteClass.INTRON_MID: 9>,
 <SiteClass.INTRON_LAST: 10>]

In [20]:
for x in SiteClass:
    print(f"{x.name} ({x.value}): {s[x.value]:,}")

UPSTREAM (1): 12,558,080
DOWNSTREAM (2): 10,410,051
UTR5 (3): 750,923
UTR3 (4): 1,561,113
CDS_FIRST (5): 697,336
CDS_MID (6): 2,395,901
CDS_LAST (7): 1,176,587
INTRON_FIRST (8): 5,153,084
INTRON_MID (9): 11,478,176
INTRON_LAST (10): 1,452,039


In [21]:
pos = ag3.snp_sites(contig="2L", field="POS")
pos

dask.array<array, shape=(48525747,), dtype=int32, chunksize=(524288,), chunktype=numpy.ndarray>